"""empty message

Revision ID: 5c17de8cdcb4
Revises: a5d6487d700c
Create Date: 2024-01-26 14:44:10.776891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c17de8cdcb4'
down_revision: Union[str, None] = 'a5d6487d700c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expansions_id', table_name='expansions')
    op.drop_table('expansions')
    op.drop_index('ix_order_item_id', table_name='order_item')
    op.drop_table('order_item')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_table('orders')
    op.drop_column('wishlist_item', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('second_phone', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('target', sa.VARCHAR(), nullable=True),
    sa.Column('date_ordered', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paymnet_type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_item_id', 'order_item', ['id'], unique=False)
    op.create_table('expansions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('date_ordered', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expansions_id', 'expansions', ['id'], unique=False)
    # ### end Alembic commands ###
