"""empty message

Revision ID: 8375a4e6754e
Revises: ff98407a4ead
Create Date: 2024-01-18 09:52:47.871345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8375a4e6754e'
down_revision: Union[str, None] = 'ff98407a4ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'amount')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
