"""empty message

Revision ID: caed1ad4f7a6
Revises: 8375a4e6754e
Create Date: 2024-01-18 10:15:09.527460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'caed1ad4f7a6'
down_revision: Union[str, None] = '8375a4e6754e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
