"""empty message

Revision ID: ff98407a4ead
Revises: 44db6f014715
Create Date: 2024-01-18 09:52:18.680891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff98407a4ead'
down_revision: Union[str, None] = '44db6f014715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'image')
    op.drop_column('products', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('amount', sa.INTEGER(), nullable=True))
    op.add_column('products', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.add_column('products', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
